#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/certbot_renew_wildcard" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT

DN="example.com"; curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/certbot_renew_wildcard?t=$(date +'%s.%N')" | bash -s -- "${DN}";

fi;
#
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/certbot_renew_wildcard_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/certbot_renew_wildcard"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d')"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); echo "Script started at [ $(date +'%Y-%m-%dT%H:%M:%S.%N%z';) ]";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  #
  # !!! REDIRECT TO "certbot_add_wildcard" RUNTIME !!!
  #      |
  #      |--> As-of June, 2020 due to certbot not offering any pure-backend methods of simplified wildcard certificate renewal (which can easily automated via a cron-job, etc. without needing to contact other services' additional APIs separately afterwards, etc. (possible for sure just not all packaged nicely through certbot, yet))
  #           |
  #           |--> e.g. you have to just recreate the wildcard certificate to renew it
  #
  DL="${HOME}"; if [ -w "/usr/local/sbin" ]; then DL="/usr/local/sbin"; fi; RUNSSL="${DL}/certbot_add_wildcard"; if [ ! -x "${RUNSSL}" ]; then wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/certbot_add_wildcard" -O "${RUNSSL}" -q; chmod 0755 "${RUNSSL}"; fi; ${RUNSSL} "${1}"; test -x /usr/local/sbin/reload_nginx && /usr/local/sbin/reload_nginx;
fi;

