#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/ddns_ufw_update" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Declare runtime variable(s)
	
	# Verbosity-level, e.g. "Verbose-ness" of runtime-script
	if [ -n "${VERBOSITY}" ] && (("${VERBOSITY}" >= "1")); then
		VERBOSE="1";
	else
		VERBOSE="0";
	fi;

	DIRNAME_LOCAL_CONFIG="/etc/ddns_ufw_update";
	mkdir -p "${DIRNAME_LOCAL_CONFIG}";

	# File containing hosts to allow through UFW
	#  |--> All lines in given whitelist file must be in a specific format/syntax
	#        |
	#        |--> Syntax:    TCP/UDP:PORT:SUBDOMAIN.DOMAIN.TLD
	#        |--> Example:   tcp:22:demo.example.com
	#
	HOSTS_WHITELIST="${DIRNAME_LOCAL_CONFIG}/hosts_whitelist";

	# Output file to hold the resolved hostnames
	HOSTS_RESOLVED="${DIRNAME_LOCAL_CONFIG}/hosts_resolved";

	# ------------------------------------------------------------
	# Function to add a rule to UFW
	add_rule() {
		local proto=$1;
		local port=$2;
		local ip=$3;
		local regex="${WHITELIST_PORT}\/${WHITELIST_PROTOCOL}.*ALLOW.*IN.*${ip}";
		local rule=$(ufw status numbered | grep $regex);
		if [ -z "$rule" ]; then
			echo "$(date +'%Y-%m-%d %H:%M:%S') | ✓ Creating Rule: ${WHITELIST_PROTOCOL}/${WHITELIST_PORT} ALLOW IN ${ip}";
			ufw allow proto ${WHITELIST_PROTOCOL} from ${ip} to any port ${WHITELIST_PORT};
		else
			if [ "$VERBOSE" == "1" ]; then echo "$(date +'%Y-%m-%d %H:%M:%S') | … No action - Rule already exists: ${WHITELIST_PROTOCOL}/${WHITELIST_PORT} ALLOW IN ${ip}"; fi;
		fi;
	}


	# ------------------------------------------------------------
	# Function to delete a rule from UFW
	delete_rule() {
		local proto=$1;
		local port=$2;
		local ip=$3;
		local regex="${WHITELIST_PORT}\/${WHITELIST_PROTOCOL}.*ALLOW.*IN.*${ip}";
		local rule=$(ufw status numbered | grep $regex);
		if [ -n "$rule" ]; then
			echo "$(date +'%Y-%m-%d %H:%M:%S') | ✘ Deleting Rule: ${WHITELIST_PROTOCOL}/${WHITELIST_PORT} ALLOW IN ${ip}";
			ufw delete allow proto ${WHITELIST_PROTOCOL} from ${ip} to any port ${WHITELIST_PORT};
			# ex) ufw allow proto tcp from any to any port 80,443
		else
			if [ "$VERBOSE" == "1" ]; then echo "$(date +'%Y-%m-%d %H:%M:%S') | … No action - Rule already deleted: ${WHITELIST_PROTOCOL}/${WHITELIST_PORT} ALLOW IN ${ip}"; fi;
		fi;
	}


	# ------------------------------------------------------------
	# Main Runtime
	#   |--> Iterate through the whitelisted hostnames (found in the whitelist-file) one-by-one
	#
	sed '/^[[:space:]]*$/d' ${HOSTS_WHITELIST} | sed '/^[[:space:]]*#/d' | while read EACH_WHITELIST_LINE;	do
		if [ -n "${EACH_WHITELIST_LINE}" ]; then

			echo "------------------------------------------------------------";
			echo "EACH_WHITELIST_LINE = [ ${EACH_WHITELIST_LINE} ]";

			WHITELIST_PROTOCOL=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f1);
			WHITELIST_PORT=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f2);
			WHITELIST_HOST=$(echo ${EACH_WHITELIST_LINE} | cut -d: -f3);

			OLD_RESOLVED_IPV4="";
			if [ "$(echo ${WHITELIST_HOST} | tr '[:upper:]' '[:lower:]';)" == "any" ]; then
				# Allow "Any" host to be used
				CURRENT_RESOLVED_IPv4="any";
			else
				# Determine current & previous IPv4(s) for each hostname
				CURRENT_RESOLVED_IPv4=$(dig +short $host | tail -n 1);
				OLD_RESOLVED_IPV4=$(cat ${HOSTS_RESOLVED} | grep ${WHITELIST_HOST} | cut -d: -f2);
				# Remove old IPv4 rule(s)
				if [ -z ${ip} ]; then
					if [ -n "${OLD_RESOLVED_IPV4}" ]; then
						delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
					fi;
					echo "$(date +'%Y-%m-%d %H:%M:%S') Error: Hostname resolution failed for \"${WHITELIST_HOST}\" (could not be converted to an IPv4/IPv6 address)" 1>&2;
					# exit 1;
				fi;
				# Remove old whitelist-rule(s)
				if [ -n "${OLD_RESOLVED_IPV4}" ]; then
					if [ ${ip} != ${OLD_RESOLVED_IPV4} ]; then
						delete_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${OLD_RESOLVED_IPV4};
					fi;
				fi;
			fi;

			add_rule ${WHITELIST_PROTOCOL} ${WHITELIST_PORT} ${ip};

			if [ -f ${HOSTS_RESOLVED} ]; then
				sed -i.bak /^${WHITELIST_HOST}*/d ${HOSTS_RESOLVED};
			fi;

			echo "${WHITELIST_HOST}:${ip}" >> ${HOSTS_RESOLVED};

		fi;
	done;


	# ------------------------------------------------------------
	# Set ownership & privileges for the logging directory & sub-contents
	chown -R "syslog:adm" "${LOGDIR}";
	find "${LOGDIR}" -type d -print0 | xargs -0 chmod 0750; # directories 
	find "${LOGDIR}" -type f -print0 | xargs -0 chmod 0640; # files


fi;


# ------------------------------------------------------------
#
#### Setting up this file can be done via:
#
#		vi "/usr/local/sbin/ddns_ufw_update";
#
#		chmod 0755 "/usr/local/sbin/ddns_ufw_update";
#
#
#
#### The content of "/etc/ddns_ufw_update.whitelist" should match the format:
#	
#		vi "/etc/ddns_ufw_update.whitelist";
#
#		tcp:22:yourpc.no-ip.org
#
#
#
#### Shortcuts to this script, whitelist, and logfile-directory can be set via:
#	
#		mkdir -p "/root/ddns_ufw_update";
#		chmod 0700 "/root/ddns_ufw_update";
#		ln -sf "/etc/ddns_ufw_update.whitelist" "/root/ddns_ufw_update/whitelist";
#		ln -sf "/usr/local/sbin/ddns_ufw_update" "/root/ddns_ufw_update/runtime";
#		ln -sf "/var/log/ddns_ufw_update" "/root/ddns_ufw_update/logs";
#
#
#
#### A crontab entry for executing the script every 3 minutes could look like this:
#
#		crontab -e
#
#		*/3 * * * * sudo "ddns_ufw_update"
#
#
#
# ------------------------------------------------------------
#
# Citation(s)
#
#		Thanks to stackoverflow user "Force" on forum: https://superuser.com/questions/646958/ufw-rules-for-specific-host-dynamic-dns
#		Original script from https://notepad2.blogspot.com/2012/06/shell-script-update-ufw-rules-for-hosts.html
#
# ------------------------------------------------------------