#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/disable_ipv6" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------

	CONF_DISABLE_IPV6="/etc/sysctl.d/99-zero-ipv6-traffic.conf";

	RELOAD_SYSCTL="";

	FORCE_RECREATE_CONFIG="0";

	APPLY_DISABLE="1";
	
	if [ -n "${1}" ]; then
		if [ "${1}" == "revert" ]; then
			APPLY_DISABLE="0";
		fi;
		if [ "${1}" == "force" ]; then
			FORCE_RECREATE_CONFIG="1"; # Force-recreate this runtime's unique config-file
		fi;
	fi;

	if [ ! -f "${CONF_DISABLE_IPV6}" ]; then
		echo "$(date +'%Y-%m-%d %H:%M:%S') Creating sysctl file \"${CONF_DISABLE_IPV6}\"...";
		echo -n "" > "${CONF_DISABLE_IPV6}";
		RELOAD_SYSCTL="1";
	elif [ "${FORCE_RECREATE_CONFIG}" == "1" ]; then
		echo "$(date +'%Y-%m-%d %H:%M:%S') Overwriting sysctl file \"${CONF_DISABLE_IPV6}\"...";
		echo -n "" > "${CONF_DISABLE_IPV6}";
		RELOAD_SYSCTL="1";
	fi;

	# Rules to ensure get applied to sysctl in current environment & on every boot henceforth
	DISABLE_IPV6_ALL="net.ipv6.conf.all.disable_ipv6";
	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_ALL} | grep ${APPLY_DISABLE})" ]; then
		echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_ALL} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
		echo "${DISABLE_IPV6_ALL} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
		RELOAD_SYSCTL="${APPLY_DISABLE}";
	fi;

	DISABLE_IPV6_DEF="net.ipv6.conf.default.disable_ipv6";
	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_DEF} | grep ${APPLY_DISABLE})" ]; then
		echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_DEF} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
		echo "${DISABLE_IPV6_DEF} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
		RELOAD_SYSCTL="1";
	fi;

	DISABLE_IPV6_LO="net.ipv6.conf.lo.disable_ipv6";
	if [ -z "$(cat ${CONF_DISABLE_IPV6} | grep ${DISABLE_IPV6_LO} | grep ${APPLY_DISABLE})" ]; then
		echo "$(date +'%Y-%m-%d %H:%M:%S') Adding \"${DISABLE_IPV6_LO} = ${APPLY_DISABLE}\" to sysctl file \"${CONF_DISABLE_IPV6}\"...";
		echo "${DISABLE_IPV6_LO} = ${APPLY_DISABLE}" >> "${CONF_DISABLE_IPV6}";
		RELOAD_SYSCTL="1";
	fi;

	# If we modified any files, update sysctl's config-values
	if [ -n "${RELOAD_SYSCTL}" ]; then
		chmod 0644 "${CONF_DISABLE_IPV6}";
		chown root:root "${CONF_DISABLE_IPV6}";
		sysctl --system;
	else
		echo "$(date +'%Y-%m-%d %H:%M:%S') No changes required for sysctl file \"${CONF_DISABLE_IPV6}\" (already up-to-date)";
	fi;
	
fi;
