#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/docker_log_limiter" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [ 0 -eq 1 ]; then # RUN THIS SCRIPT

sudo -i;  # Masquerade as the "root" user

LOCAL_SBIN="/usr/local/sbin/docker_log_limiter"; curl -H 'Cache-Control: no-cache' -o "${LOCAL_SBIN}" -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/docker_log_limiter"; chmod 0755 "${LOCAL_SBIN}"; "${LOCAL_SBIN}";


fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Set the max-filesize for a given docker's logfile

	DOCKER_GLOBAL_CONFIG="/etc/docker/daemon.json";

	MAX_LOG_FILESIZE="10m";

	echo "";
	if [ -f "${DOCKER_GLOBAL_CONFIG}" ]; then
		echo -e "Please ensure the following json exists in the docker global-config file found @ \"${DOCKER_GLOBAL_CONFIG}\":\n\n{\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"${MAX_LOG_FILESIZE}\",\n    \"max-file\": \"3\",\n  }\n}" >> "${DOCKER_GLOBAL_CONFIG}";
	else
		echo -e "{\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"${MAX_LOG_FILESIZE}\",\n    \"max-file\": \"3\"\n  }\n}" >> "${DOCKER_GLOBAL_CONFIG}";
		echo "Applied filesize-restriction to all docker containers --> max-size: \"${MAX_LOG_FILESIZE}\"";
		echo "";
		echo "Reloading daemon & restarting docker-service (to apply updated configuration)...";
		systemctl daemon-reload;
		systemctl restart docker;
		echo "";
		echo "Done";
	fi;
	echo "";

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   docs.docker.com  |  "Configure logging drivers | Docker Documentation"  |  https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver
#
# ------------------------------------------------------------