#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/enable_ipv6" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------


# Call  [ disable_ipv6 --enable ]
curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/disable_ipv6?t=$(date --utc +'%s.%N';)" | bash -s -- --enable;


# ------------------------------------------------------------