#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/get_services" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  if [ -z "$1" ]; then
    # Show all services
    # SERVICE_LIST_ALL=$(systemctl list-unit-files --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null');
    /bin/systemctl list-unit-files --no-legend --no-pager --full | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null';

  else
    # Search for one, specific service
    SERVICE_NAME="${1}";
    # SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
    SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
    if [ ${SERVICE_RET_CODE} -eq 0 ]; then
      # If service IS found: Show service & exit with return-code 0
      /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;
      exit 0;
    else
      # If service is NOT found: Alert user & exit with return-code 1
      echo "Error:  Service \"${1}\" not found locally";
      exit 1;
    fi;

  fi;

  ###	List only services matching a given state, such as "enabled"
  ### /bin/systemctl list-unit-files --state=enabled --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | sort 2> '/dev/null';

fi;

# ------------------------------------------------------------
# SERVICE NAMING-CONVENTION/NAME-SYNTAX
#   |--> From services(5) in the Linux manual:
#
# "...
#
# The service-name should begin in the first column of the file, since leading spaces are not stripped.
# service-names can be any printable characters excluding space and tab.
# However, a conservative choice of characters should be used to minimize compatibility problems.
# For example, a-z, 0-9, and hyphen (-) would seem a sensible choice.
#
# ..."
#
#
# ------------------------------------------------------------
#
# Citation(s)
#
#   askubuntu.com  |  "How to list all enabled services from systemctl?"  |  https://askubuntu.com/a/795245
#
#   cyberciti.biz  |  "Red Hat / CentOS Check and List Running Services Linux Command"  |  https://www.cyberciti.biz/faq/check-running-services-in-rhel-redhat-fedora-centoslinux/
#
#   linux.die.net  |  "services(5) - Linux man page"  |  https://linux.die.net/man/5/services
#
#   unix.stackexchange.com  |  "What does “systemctl daemon-reload” do?"  |  https://unix.stackexchange.com/a/364787
#
# ------------------------------------------------------------