#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_java" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q && chmod 0755 "/usr/local/sbin/install_java" && /usr/local/sbin/install_java;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	#
	# Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
	#
	if [ 0 -eq 1 ]; then


	test $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 && apt-get -y update && apt-get -y install openjdk-8-jre-headless; test $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 && yum -y check-update && yum -y install java-1.8.0-openjdk-headless; # Install Java SE8 (one-liner)


	fi;
	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
		#
		# Debian, Ubuntu, etc.
		#   |-->  openjdk-$(version)-jre-headless
		#

		# apt-cache search --names-only openjdk 8 headless | awk '{print $1}';

		apt-get -y update;
		apt-get -y install openjdk-8-jre-headless;

	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
		#
		# Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
		#   |-->  java-$(version)-openjdk-headless
		#
		
		# yum search java headless 1.8 --exclude=*debug*

		yum -y check-update;
		yum -y install java-1.8.0-openjdk-headless;

	fi;

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   linode.com  |  "Install Java on Centos 7"  |  https://www.linode.com/docs/development/java/install-java-on-centos/#install-java-runtime-environment-java-jre
#
#   openjdk.java.net  |  "How to download and install prebuilt OpenJDK packages"  |  https://openjdk.java.net/install/
#
# ------------------------------------------------------------