#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_flux" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT REMOTELY

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_flux?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_flux_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_flux"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d')"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date +'%Y-%m-%dT%H:%M:%S.%N%z';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  EXIT_CODE=0;

  # Install/Update 'flux' via convenience script  -  https://fluxcd.io/docs/installation/#install-the-flux-cli
  echo "";
  echo "[INFO]  Calling [ curl -s \"https://fluxcd.io/install.sh\" | bash; ]...";
  curl -s "https://fluxcd.io/install.sh" | bash;

  echo "";
  echo "[INFO]  Calling [ command -v flux; ]...";
  command -v flux;

  if [ -n "$(command -v flux 2>'/dev/null';)" ]; then

    # Verify that flux is installed by getting the installed version from it
    echo "";
    echo "Calling [ flux --version; ]...";
    flux --version;

  else

    echo "";
    echo "Error:  Unable to install Flux";
    EXIT_CODE=1;

  fi;
  # ------------------------------
  echo "";
  exit ${EXIT_CODE};
  # ------------------------------
fi;


# ------------------------------------------------------------
#
# Citation(s)
# 
#   github.com  |  "GitHub - fluxcd/flux2: Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit."  |  https://github.com/fluxcd/flux2
# 
#   fluxcd.io  |  "Installation | Flux"  |  https://fluxcd.io/docs/installation/#install-the-flux-cli
#
# ------------------------------------------------------------