#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_7z" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [ 0 -eq 1 ]; then  # RUN THIS SCRIPT

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_7z?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_7z_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_7z"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
# ------------------------------------------------------------
# Install 7-Zip Package

  if [ $(which 7z 2>'/dev/null' | wc -l;) -eq 0 ]; then
    if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
      apt-get -y update;
      apt-get -y install p7zip-full;
    elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
      wget "https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-10.el7.x86_64.rpm";
      wget "https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-10.el7.x86_64.rpm";
      sudo rpm -U --quiet "p7zip-16.02-10.el7.x86_64.rpm";
      sudo rpm -U --quiet "p7zip-plugins-16.02-10.el7.x86_64.rpm";
      rm -f "p7zip-16.02-10.el7.x86_64.rpm";
      rm -f "p7zip-plugins-16.02-10.el7.x86_64.rpm";
    fi;
  fi;

fi;


# ------------------------------------------------------------
# Citation(s)
# 
#   packages.debian.org  |  "Debian -- Details of package p7zip-full in sid"  |  https://packages.debian.org/sid/p7zip-full
# 
#   www.7-zip.org  |  "7-Zip Download"  |  https://www.7-zip.org/download.html
# 
# ------------------------------------------------------------