#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_ntp" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_ntp" -O "/usr/local/sbin/install_ntp" -q && chmod 0755 "/usr/local/sbin/install_ntp" && /usr/local/sbin/install_ntp;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Install NTP (Time Sync) package "chrony"
	echo "";
	read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync to NTP server(s), now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		PACKAGE_NAME="chrony";
		SERVICE_NAME="${PACKAGE_NAME}d";
		if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
			apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Install Java SE8 for Debian, Ubuntu, etc.
		elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
			yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Install Java SE8 for Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
		fi;
		timedatectl set-ntp yes;
		systemctl restart "${SERVICE_NAME}";
		echo "";
		read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync the hardware clock, now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
		echo "";
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			hwclock --systohc;
			timedatectl set-ntp yes;
		fi;
	fi;
fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   linode.com  |  "Install Java on Centos 7"  |  https://www.linode.com/docs/development/java/install-java-on-centos/#install-java-runtime-environment-java-jre
#
#   openjdk.java.net  |  "How to download and install prebuilt OpenJDK packages"  |  https://openjdk.java.net/install/
#
# ------------------------------------------------------------