#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_java" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q && chmod 0755 "/usr/local/sbin/install_java" && /usr/local/sbin/install_java;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
		PACKAGE_NAME="openjdk-8-jre-headless"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Debian, Ubuntu, etc.
	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
		PACKAGE_NAME="java-1.8.0-openjdk-headless"; yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
	fi;


	# ------------------------------------------------------------
	# Show Java runtime-version
	if [ $(which java 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
		echo "";
		echo "------------------------------------------------------------";
		echo "Into:  Calling [ java -XshowSettings:properties -version 2>&1; ]...";
		if [ $(which java 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
			# Note: Java outputs to STDERR (2) by default - Redirect its output to STDOUT (1) by using 2>&1
			JAVA_ALL_SETTINGS="$(java -XshowSettings:properties -version 2>&1;)"; echo "JAVA_ALL_SETTINGS = [ ${JAVA_ALL_SETTINGS} ]"; 
			LOCAL_JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 | sed -rne 's/^\s*java.home = (.+)\s*$/\1/p';); echo "LOCAL_JAVA_HOME = [ ${LOCAL_JAVA_HOME} ]"; 
		fi;
		echo "------------------------------------------------------------";
	fi;


fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   docs.oracle.com  |  "java.awt (SE-8) - Class Font"  |  https://docs.oracle.com/javase/8/docs/api/java/awt/Font.html
#
#   docs.oracle.com  |  "Font Configuration Files"  |  https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html
#
#   linode.com  |  "Install Java on Centos 7"  |  https://www.linode.com/docs/development/java/install-java-on-centos/#install-java-runtime-environment-java-jre
#
#   openjdk.java.net  |  "How to download and install prebuilt OpenJDK packages"  |  https://openjdk.java.net/install/
#
#   umd.edu  |  "Finding and Setting JAVA HOME"  |  http://sbndev.astro.umd.edu/wiki/Finding_and_Setting_JAVA_HOME
#
# ------------------------------------------------------------