#!/bin/bash

yum -y check-update;
yum -y install open-vm-tools;

### Once-installed, manually run:
# echo "To use VMware Tools, manually run   [ /usr/bin/vmware-user ]";


echo "";
echo "$(date +'%Y-%m-%d_%H-%M-%S')  |  Reboot required to finish installing VMWare-Tools";
read -p " --> Reboot, now? (y/n)  " -n 1 -t 60 -r;
echo "";
if [[ $REPLY =~ ^[Yy]$ ]]; then
	reboot now;
fi;

# ------------------------------------------------------------
#
# Citation(s)
#
#   shellhacks.com  |  "HowTo: Install VMware Tools on CentOS/RHEL"  |  https://www.shellhacks.com/install-vmware-tools-centos-rhel/
#
# ------------------------------------------------------------