#!/bin/bash

yum -y check-update; yum -y install open-vm-tools;

### Once-installed, manually run:
/usr/bin/vmware-user


# ------------------------------------------------------------
#
# Citation(s)
#
#   shellhacks.com  |  "HowTo: Install VMware Tools on CentOS/RHEL"  |  https://www.shellhacks.com/install-vmware-tools-centos-rhel/
#
# ------------------------------------------------------------