#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_jp" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then # RUN THIS SCRIPT

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_jp?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_jp_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_jp"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  #
  # Install JP (command-line JMESPath interpreter-processor)
  #
  EXIT_CODE=0;
  GITHUB_OWNER="${GITHUB_OWNER:-jmespath}";  # Override with any github repo owner
  GITHUB_REPO="${GITHUB_REPO:-jp}";  # Override with repo name owned by github repo owner
  VERSION_CLI="${VERSION_CLI:---version 2>'/dev/null' | rev | cut -d' ' -f1 | rev}";  # cli command to run to get the version out of the repo's package
  FULLPATH_LOCAL_PKG="${FULLPATH_LOCAL_PKG}";  # local filepath to install the package onto
  INSTALL_PKG=1;
  # ------------------------------
  # Determine OS and processor architecture
  OS_NAME="";
  if [ "$(uname -s)" == "Linux" ] || [[ "${OSTYPE}" == "linux"* ]]; then
    # Install pkg for Linux
    FULLPATH_LOCAL_PKG="/usr/bin/${GITHUB_REPO}";
    OS_NAME="linux";
    if [[ -n "$(command -v dpkg 2>'/dev/null';)" ]]; then
      PROCESSOR_ARCH="$(dpkg --print-architecture;)";
    fi;
  elif [[ "${OSTYPE}" == "darwin"* ]]; then
    # Install pkg for MacOS
    FULLPATH_LOCAL_PKG="/usr/bin/${GITHUB_REPO}";
    OS_NAME="darwin";
  else
    # Install pkg for Windows
    FULLPATH_LOCAL_PKG="${HOME}/bin/${GITHUB_REPO}.exe";
    OS_NAME="windows";
  fi;
  PKG_NAME="$(basename "${FULLPATH_LOCAL_PKG}")";
  # ------------------------------
  # Get package's latest release version
  OS_ARCH="${OS_NAME}-${PROCESSOR_ARCH:-amd64}";
  PKG_RELEASES_URL="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases";
  RELEASE_INFO=$(curl -sL "${PKG_RELEASES_URL}" | grep '<a href' | grep "${GITHUB_OWNER}/${GITHUB_REPO}/releases/download" | grep "${OS_ARCH}" | head -n 1 | sed -rne "s/^.+<a href=\"((https:\\/\\/github\.com)?\\/${GITHUB_OWNER//\//\\\/}\\/${GITHUB_REPO//\//\\\/}\/releases\/download\/([^\"\\/]+)\/([^\"-]+-${OS_ARCH}[^\"]*))\".+$/\1\n\3/pi";);
  if [[ -z "${RELEASE_INFO}" ]]; then
    echo "";
    echo "Error:  No data returned from URL [ ${PKG_RELEASES_URL} ] while attempting to obtain latest release info";
  else
    RELEASE_URL="$(if [[ "$(echo "${RELEASE_INFO}" | head -n 1 | grep 'https://github.com' | wc -l;)" -eq 0 ]]; then echo -n "https://github.com"; fi;)$(echo -n "${RELEASE_INFO}" | head -n 1)";
    RELEASE_FILENAME="$(echo "${RELEASE_URL}" | rev | cut -d'/' -f1 | rev;)";
    RELEASE_VERSION="$(echo "${RELEASE_INFO}" | tail -n 1;)";
    # Handle scenarios where the package is already installed
    if [[ -f "${FULLPATH_LOCAL_PKG}" ]]; then
      # Package is already installed
      # Get the locally installed package's version
      LOCAL_VERSION="$(eval "${FULLPATH_LOCAL_PKG} ${VERSION_CLI}";)";
      if [[ -z "${LOCAL_VERSION}" ]] ; then
        # Installed package's version was unable to be obtained - remove it
        INSTALL_PKG=1;
        echo "";
        echo "Warning:  Unable to obtain version from file \"${FULLPATH_LOCAL_PKG}\" - Removing...";
        rm -rfv "${FULLPATH_LOCAL_PKG}";
      elif [[ -n "${LOCAL_VERSION}" ]] && [[ -n "${RELEASE_VERSION}" ]] && [[ "${LOCAL_VERSION}" == "${RELEASE_VERSION}" ]]; then
        # Installed version matches latest version
        INSTALL_PKG=0;
        echo "";
        echo "Info:  Package \"${PKG_NAME}\" is already installed and up-to-date with the latest version [ ${RELEASE_VERSION} ]";
      else
        # Installed version differs from latest version
        READ_TIMEOUT=60;
        USER_RESPONSE="";
        echo "";
        read -p "Info:  Do you want to update package \"${PKG_NAME}\" from version [ ${LOCAL_VERSION} ] to version [ ${RELEASE_VERSION} ]?  (press 'y' to confirm)  " -a USER_RESPONSE -n 1 -t ${READ_TIMEOUT} <'/dev/tty'; EXIT_CODE=${?};
        echo "";
        if [[ "${USER_RESPONSE}" =~ ^[Yy]$ ]]; then
          echo " |--> Confirmed";
          INSTALL_PKG=1;
        else
          echo " |--> Denied";
          INSTALL_PKG=0;
        fi;
      fi;
    fi;
  fi;
  # ------------------------------
  # Download/Install the package
  if [[ "${INSTALL_PKG}" -eq 1 ]]; then
    if [[ -n "${RELEASE_URL}" ]]; then
      echo "";
      echo "Info:  Downloading/Installing package \"${PKG_NAME}\" to local filepath \"${FULLPATH_LOCAL_PKG}\"...";
      if [[ ! -d "$(dirname "${FULLPATH_LOCAL_PKG}";)" ]]; then
        mkdir -pv "$(dirname "${FULLPATH_LOCAL_PKG}";)";
      fi;
      if [[ -f "${FULLPATH_LOCAL_PKG}" ]]; then
        rm -rfv "${FULLPATH_LOCAL_PKG}";
      fi;
      # Download the package
      curl -sL -o "${FULLPATH_LOCAL_PKG}" "${RELEASE_URL}";
      # Set file permissions on the package
      chmod 0755 "${FULLPATH_LOCAL_PKG}";
    fi;
    LOCAL_VERSION="$(eval "${FULLPATH_LOCAL_PKG} ${VERSION_CLI}";)";
    if [[ -z "${LOCAL_VERSION}" ]] ; then
      # Package 
      echo "";
      echo "Info:  Installing package \"${PKG_NAME}\" (via apt)...";
      if [[ -n "$(command -v apt 2>'/dev/null';)" ]]; then  # Distros: Debian, Ubuntu, etc.
        # Fallback package installation --> using apt
        apt-get -y update; apt-get -y install "jp";
      fi;
    fi;
  fi;
  # Get the locally installed package's version
  if [[ -f "${FULLPATH_LOCAL_PKG}" ]] ; then
    # Package found locally
    LOCAL_VERSION="$(eval "${FULLPATH_LOCAL_PKG} ${VERSION_CLI}";)";
    echo "";
    echo "Info:  Package \"${PKG_NAME}\" found locally w/ filepath [ ${FULLPATH_LOCAL_PKG} ])";
    if [[ -n "${LOCAL_VERSION}" ]] ; then
      # Package version successfully obtained
      echo " |--> Info:  Package version:  [ ${LOCAL_VERSION} ]";
    else
      # Package version unable to be obtained
      echo " |--> Warning:  Package version unable to be obtained";
    fi;
  else
    # Package NOT found locally
    echo "";
    echo "Error:  Package \"${PKG_NAME}\" not found locally";
    EXIT_CODE=1;
  fi;
  # ------------------------------
  exit ${EXIT_CODE};
  # ------------------------------
fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   github.com  |  "GitHub - jmespath/jp: Command line interface to JMESPath - http://jmespath.org"  |  https://github.com/jmespath/jp
#
#   www.devmanuals.net  |  "How to install jp on Ubuntu 20.04 (Focal Fossa)?"  |  https://www.devmanuals.net/install/ubuntu/ubuntu-20-04-focal-fossa/installing-jp-on-ubuntu20-04.html
#
# ------------------------------------------------------------