#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_kubectl" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT REMOTELY

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_kubectl?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_kubectl_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_kubectl"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d')"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date +'%Y-%m-%dT%H:%M:%S.%N%z';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  # To-Do: Replace with installation logic for kubectl
  echo "";
  echo "Please refer to documentation article [ Install and Set Up kubectl on Linux | Kubernetes ] at URL [ https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ ]";
  echo "";

  if [ -n "$(command -v kubectl 2>'/dev/null';)" ]; then
    # Verify that kubectl is installed by getting the installed version from it
    echo "";
    echo "Calling [ kubectl version --short; ]...";
    kubectl version --short;
  fi;

fi;


# ------------------------------------------------------------
#
# Citation(s)
# 
#   kubernetes.io  |  "Install and Set Up kubectl on Linux | Kubernetes"  |  https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
#
# ------------------------------------------------------------