#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_kdump" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_kdump" -O "/usr/local/sbin/install_kdump" -q && chmod 0755 "/usr/local/sbin/install_kdump" && /usr/local/sbin/install_kdump;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	#
	# Install/setup kernel crash dump logging for use during RCA auditing workflows
	#
	SERVICE_NAME="kdump";

	if [ $(which kdump 2>'/dev/null' | wc -l;) -eq 0 ]; then
		if [ $(which apt 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Debian, Ubuntu, etc.
			apt-get -y install linux-crashdump;
		elif [ $(which yum 2>'/dev/null' | wc -l;) -gt 0 ]; then # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
			yum -y install kexec-tools;
		fi;
	fi;

	# Verify that taget service is enabled
	if [ "$(systemctl is-enabled ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
		systemctl enable ${SERVICE_NAME};
	fi;

	# Verify that taget service is active
	if [ "$(systemctl is-active ${SERVICE_NAME} > /dev/null 2>&1; echo $?;)" != "0" ]; then
		systemctl start ${SERVICE_NAME};
	fi;

	echo "";
	echo "  Use command \"df -hT\" to determine log output filesystem's type (under column \"Type\") as well as Filesystem path (under column \"Mounted on\")";
	echo "";

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   access.redhat.com  |  "Chapter 7. Kernel crash dump guide Red Hat Enterprise Linux 7 | Red Hat Customer Portal"  |  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/kernel_administration_guide/kernel_crash_dump_guide
#
#   help.ubuntu.com  |  "Kernel Crash Dump"  |  https://help.ubuntu.com/lts/serverguide/kernel-crash-dump.html
#
# ------------------------------------------------------------