#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_helm" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT REMOTELY

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_helm?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_helm_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_helm"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  # Ensure that helm is installed
  if [ -n "$(command -v helm 2>'/dev/null';)" ]; then

    # Helm is already installed
    echo "";
    echo "(Skipped) Command \"helm\" already exists with filepath \"$(command -v helm;)\"";

  else

    # Helm is NOT installed --> Install it
    echo "";
    if [ -n "$(command -v apt 2>'/dev/null';)" ]; then # Distros: Debian, Ubuntu, etc.

      # Install 'helm' via package manager  -  https://helm.sh/docs/intro/install/#from-apt-debianubuntu
      curl "https://baltocdn.com/helm/signing.asc" | apt-key add -;
      apt-get -y install apt-transport-https;
      echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee "/etc/apt/sources.list.d/helm-stable-debian.list";
      apt-get -y update;
      apt-get -y install helm;

    else # Distros:  Non-debian
    
      # Install 'helm' via convenience script  -  https://helm.sh/docs/intro/install/#from-script
      curl "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3" | bash;

    fi;

    echo "";
    echo "Calling [ command -v helm; ]...";
    command -v helm;

  fi;

  # Verify that helm is installed by getting the installed version from it
  echo "";
  echo "Calling [ helm version --short; ]...";
  helm version --short;

  echo "";

fi;


# ------------------------------------------------------------
#
# Citation(s)
# 
#   helm.sh  |  "Helm | Installing Helm"  |  https://helm.sh/docs/intro/install
#
# ------------------------------------------------------------