#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_ssh_server" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_ssh_server?t=$(date +'%s.%N')" | bash;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  # Install Java SE8 (Standard Edition 8) "Headless" version (e.g. "CLI" or "Minimal")
  SERVICE_NAME="java";

  if [[ -n "$(command -v apt 2>'/dev/null';)" ]]; then  # Distros: Debian, Ubuntu, etc.
    PACKAGE_NAME="openssh-server"; apt-get -y update; apt-get -y install "${PACKAGE_NAME}";
  # elif [[ -n "$(command -v yum 2>'/dev/null';)" ]]; then  # Distros: Fedora, Oracle Linux, Red Hat Enterprise Linux, CentOS, etc.
  #   PACKAGE_NAME="openssh-server"; yum -y check-update; yum -y install "${PACKAGE_NAME}";
  else
    echo "";
    echo "Error:  Environment not (yet) supported, exiting...";
    exit 1;
  fi;

  # ------------------------------------------------------------
  # Setup Firewall
  curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/sync_cloud_infrastructure?t=$(date +'%s.%N')" | bash -s -- --ufw;


fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   linuxize.com  |  "How to Enable SSH on Ubuntu 18.04 | Linuxize"  |  https://linuxize.com/post/how-to-enable-ssh-on-ubuntu-18-04/
#
# ------------------------------------------------------------