#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_rclone" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [ 0 -eq 1 ]; then  # RUN THIS SCRIPT

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_rclone" -O "/usr/local/sbin/install_rclone" -q && chmod 0755 "/usr/local/sbin/install_rclone" && /usr/local/sbin/install_rclone;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else

	curl "https://rclone.org/install.sh" | bash;

fi;


# ------------------------------------------------------------
# Citation(s)
# 
#   docs.min.nio  |  "MinIO | Rclone with MinIO Server- Cookbook/Recipe"  |  https://docs.minio.io/docs/rclone-with-minio-server
# 
#   rclone.org  |  "rclone - rsync for cloud storage"  |  https://rclone.org/
# 
# ------------------------------------------------------------