#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_speedtest" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT REMOTELY

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_speedtest?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_speedtest_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_speedtest"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  #
  # Ensure that prerequisite packages are installed
  #
  unset PREREQ_CMD_PKG_ARR; declare -a PREREQ_CMD_PKG_ARR; # [Re-]Instantiate bash array
  PREREQ_CMD_PKG_ARR+=("pip|python3-pip");
  PREREQ_CMD_PKG_ARR+=("python3|python3");
  APT_UPDATE_PERFORMED=0;
  for EACH_PREREQ_CMD_PKG in "${PREREQ_CMD_PKG_ARR[@]}"; do
    EACH_COMMAND="$(echo "${EACH_PREREQ_CMD_PKG}" | cut -d'|' -f1;)";
    EACH_PACKAGE="$(echo "${EACH_PREREQ_CMD_PKG}" | cut -d'|' -f2;)";
    if [ -z "$(command -v ${EACH_COMMAND} 2>'/dev/null';)" ]; then
      echo "";
      echo "Info:  Installing package \"${EACH_PACKAGE}\" (contains command \"${EACH_COMMAND}\")...";
      if [[ "${APT_UPDATE_PERFORMED}" -eq 0 ]]; then
        sudo apt-get -y update;
        APT_UPDATE_PERFORMED=1;
      fi;
      sudo apt-get -y install "${EACH_PACKAGE}";
    fi;
  done;
  #
  # Remove deprecated package(s)
  #
  if [[ "$(dpkg -l speedtest-cli 1>'/dev/null' 2>&1; echo ${?};)" -eq 0 ]]; then
    sudo apt-get -y remove "speedtest-cli";
  fi;
  #
  # Install speedtest python3 package
  #
  if [[ "$(python -c "import speedtest" 1>'/dev/null' 2>&1; echo ${?};)" -ne 0 ]]; then
    echo "Info:  Installing python3 package \"speedtest-cli\" (contains command \"speedtest\")...";
    pip install "speedtest-cli";
  fi;

  # Verify that package is installed by getting the installed version from it
  echo "";
  echo "Info:  Calling [ ${COMMAND_NAME} --version; ]...";
  ${COMMAND_NAME} --version;

  # Show basic usage for the package
  echo "";
  echo "Info:  To run a verbose speedtest, run [ speedtest; ]";
  echo "";
  echo "Info:  To run a quiet speedtest, run [ speedtest --simple; ]";
  echo "";

fi;


# ------------------------------------------------------------
#
# Citation(s)
# 
#   github.com  |  "GitHub - sivel/speedtest-cli: Command line interface for testing internet bandwidth using speedtest.net"  |  https://github.com/sivel/speedtest-cli#installation
# 
#   phoenixnap.com  |  "How to Test Network Speed in Linux {9 Tools} | phoenixNAP KB"  |  https://phoenixnap.com/kb/linux-network-speed-test
#
# ------------------------------------------------------------