#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_kubelogin" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then # RUN THIS SCRIPT

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/main/usr/local/sbin/install_kubelogin?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_kubelogin_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_kubelogin"; fi;
mkdir -p "${LOGDIR}"; chown "$(stat -c '%u:%g' "$(dirname "${LOGDIR}";)";)" "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  #
  # Install kubelogin (Azure RBAC for Kubernetes Authorization Utility - avoids interactive login prompts which hang & timeout)
  #
  EXIT_CODE=0;
  # Install unzip (prereq)
  if [[ -z "$(command -v unzip 2>'/dev/null';)" ]]; then
    echo "Calling [ apt-get -y update; apt-get -y install unzip; ]...";
    apt-get -y update; apt-get -y install unzip;
  fi;
  # Install wget (prereq)
  if [[ -z "$(command -v wget 2>'/dev/null';)" ]]; then
    echo "Calling [ apt-get -y update; apt-get -y install wget; ]...";
    apt-get -y update; apt-get -y install wget;
  fi;
  # Install kubelogin
  if [[ -z "$(command -v kubelogin 2>'/dev/null';)" ]]; then
    KUBELOGIN_DOWNLOAD_URL="https://github.com/Azure/kubelogin/releases/download/v0.0.25/kubelogin-linux-amd64.zip";
    OUTFILE="/install/kubelogin/$(basename "${KUBELOGIN_DOWNLOAD_URL}";)";
    KUBELOGIN_BIN_PATH="/usr/local/bin/kubelogin";
    mkdir -p "$(dirname "${OUTFILE}";)";
    wget -q "${KUBELOGIN_DOWNLOAD_URL}" -O "${OUTFILE}"; WGET_EXIT_CODE=${?};
    if [[ -f "${OUTFILE}" ]] && [[ "${WGET_EXIT_CODE}" -eq 0 ]]; then
      unzip -qq "${OUTFILE}" -d "$(dirname "${OUTFILE}";)/"
      mv --no-clobber "$(dirname "${OUTFILE}";)/bin/linux_amd64/kubelogin" "${KUBELOGIN_BIN_PATH}";
    else
      echo "Error while attempting to download package archive";
      EXIT_CODE=$(( ${EXIT_CODE:-0} + 1 )); echo "EXIT_CODE = [ ${EXIT_CODE} ]";
    fi;
    if [[ -f "${KUBELOGIN_BIN_PATH}" ]]; then
      echo "Downloaded kubelogin executable to path \"${KUBELOGIN_BIN_PATH}\"";
    else
      EXIT_CODE=$(( ${EXIT_CODE:-0} + 1 )); echo "EXIT_CODE = [ ${EXIT_CODE} ]";
    fi;
    rm -rf "$(dirname "${OUTFILE}";)";
  fi;
  exit ${EXIT_CODE};
  # ------------------------------
fi;


# ------------------------------------------------------------