#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_rundeck" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT

# wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_rundeck" -O "/usr/local/sbin/install_rundeck" -q && chmod 0755 "/usr/local/sbin/install_rundeck" && /usr/local/sbin/install_rundeck;

curl -sL mcavallo.com | bash; install_rundeck --force;

fi;
#
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_rundeck_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_rundeck"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  #
  # Install Docker for Linux
  #
  curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_docker?t=$(date +'%s.%N')" | bash;


  # ------------------------------------------------------------
  #
  # Install RunDeck CI/CD Server (as a docker)
  #

  if [ ! -d "/rundeck/data" ]; then
    mkdir -p "/rundeck/data";
  fi;

  if [ ! -f "/rundeck/docker-compose.yml" ]; then
    curl -o "/rundeck/docker-compose.yml" "https://raw.githubusercontent.com/rundeck/docker-zoo/master/basic/docker-compose.yml";
  fi;

  docker-compose -f "/rundeck/docker-compose.yml" up -d;

  exit ${EXIT_CODE};

fi;

# ------------------------------------------------------------
# Citation(s)
#
#   docs.rundeck.com  |  "Installing on CentOS or Red Hat Linux distributions | Rundeck Docs"  |  https://docs.rundeck.com/docs/administration/install/linux-rpm.html#open-source-rundeck
#
#   hub.docker.com  |  "rundeck/rundeck - Docker Hub"  |  https://hub.docker.com/r/rundeck/rundeck/
#
#   raw.githubusercontent.com  |  "docker-zoo/basic at master · rundeck/docker-zoo · GitHub"  |  https://raw.githubusercontent.com/rundeck/docker-zoo/master/basic/docker-compose.yml
#
# ------------------------------------------------------------