#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_jenkins" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_jenkins" -O "/usr/local/sbin/install_jenkins" -q && chmod 0755 "/usr/local/sbin/install_jenkins" && /usr/local/sbin/install_jenkins;

fi;
#
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Instantiate runtime variables

	# Docker-based installs:
	#	"/usr/local/bin/create_docker_jenkins"
	#  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
	#  |--> docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkins:alpine

	SERVICE_NAME="jenkins";

	EXIT_CODE=1;
	
	SERVICE_RESTART_REQD=0;

	APT_PKG_JDK="default-jdk-headless";
	APT_PKG_JRE="default-jre-headless";
	APT_PKG_JENKINS="jenkins";

	START_SECONDS_NANOSECONDS=$(date +'%s.%N');
	START_EPOCHSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 1);
	# START_NANOSECONDS=$(echo ${START_SECONDS_NANOSECONDS} | cut --delimiter '.' --fields 2 | cut --characters 1-9);
	# START_MICROSECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-6);
	# START_MILLISECONDS=$(echo ${START_NANOSECONDS} | cut --characters 1-3);
	START_DATETIME="$(date --date=@${START_EPOCHSECONDS} +'%Y-%m-%d %H:%M:%S')";
	START_TIMESTAMP="$(date --date=@${START_EPOCHSECONDS} +'%Y%m%d_%H%M%S')";


	echo "------------------------------------------------------------";
	echo "";
	READ_TIMEOUT=60; read -p "NOTE:  Port 8080 must be opened to access Jenkins (required) - Continue? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
	echo "";
	if [ ${RETURN_CODE_READ} -gt 128 ]; then
		echo -e "Response timed out after ${READ_TIMEOUT}s";
		exit 1;
	elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
		echo -e "\n""Proceeding...\n";
		sleep 1;
	else
		echo "Denied - Skipping the \"${SERVICE_NAME}\" service install";
		exit 1;
	fi;

	# ------------------------------------------------------------
	# Check for the Jenkins service locally
	# SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
	# if [ ${SERVICE_RET_CODE} -eq 0 ]; then
	# 	# Jenkins is already installed
	# 	echo -e "\n""Info:  Skipping Jenkins package-install (service already exists locally)";
	# else

	# ------------------------------------------------------------
	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Debian, Ubuntu, etc.
		# ------------------------------------------------------------
		# Install Java
		# PACKAGE_APT="openjdk-8-jre-headless"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Java SE8 for Debian, Ubuntu, etc.
		wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q && chmod 0755 "/usr/local/sbin/install_java" && /usr/local/sbin/install_java;
		# ------------------------------------------------------------
		# Install Fonts (Requirement for Jenkins)
		PACKAGE_APT="ttf-dejavu"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
		PACKAGE_APT="xvfb"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Fonts
		# ------------------------------------------------------------
		# Install Jenkins
		wget -q -O - "https://pkg.jenkins.io/debian-stable/jenkins.io.key" | sudo apt-key add -; # Import Jenkins' official GPG Key
		deb "https://pkg.jenkins.io/debian-stable" binary/; # Add Jenkins' package repository
		PACKAGE_APT="jenkins"; apt-get -y update; apt-get -y install "${PACKAGE_APT}"; # Install Jenkins
		SERVICE_RESTART_REQD=1;

	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then # Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.

		# ------------------------------------------------------------
		# Install Java
		# PACKAGE_YUM="java-1.8.0-openjdk-headless"; yum -y check-update; yum -y install "${PACKAGE_YUM}"; # Install Java SE8 for Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
		wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_java" -O "/usr/local/sbin/install_java" -q && chmod 0755 "/usr/local/sbin/install_java" && /usr/local/sbin/install_java;

		# ------------------------------------------------------------
		# Install Fonts (Requirement for Jenkins)SERVICE_RESTART_REQD=1; 
		PACKAGE_YUM="dejavu-sans-fonts";    if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then yum -y check-update; yum -y install "${PACKAGE_YUM}"; SERVICE_RESTART_REQD=1; fi; # Install Fonts
		PACKAGE_YUM="fontconfig";           if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then yum -y check-update; yum -y install "${PACKAGE_YUM}"; SERVICE_RESTART_REQD=1; fi; # Install Fonts
		PACKAGE_YUM="xorg-x11-server-Xvfb"; if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then yum -y check-update; yum -y install "${PACKAGE_YUM}"; SERVICE_RESTART_REQD=1; fi; # Install Fonts

		# ------------------------------------------------------------
		# Install Jenkins
		PACKAGE_YUM="jenkins"; if [ $(yum list installed | sed -rne "s/^(${PACKAGE_YUM})\.(x86_64|noarch)\s+.+$/\1/p" | wc -l;) -eq 0 ]; then
			wget -O "/etc/yum.repos.d/jenkins.repo" "https://pkg.jenkins.io/redhat-stable/jenkins.repo";  # Add Jenkins' package repository
			rpm --import "https://pkg.jenkins.io/redhat-stable/jenkins.io.key" 2>'/dev/null'; # Import Jenkins' official GPG Key
			yum -y check-update; yum -y install "${PACKAGE_YUM}"; # Install Jenkins
			SERVICE_RESTART_REQD=1;
		fi;

	fi;


	# fi;


	sleep 3;

	# ------------------------------------------------------------
	SERVICE_RET_CODE=$(/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
	if [ ${SERVICE_RET_CODE} -eq 0 ]; then
		EXIT_CODE=0;

		# Show Jenkins' service status
		echo -e "\n""Info: Showing Jenkins' Service-Status";
		echo -e "  |--> Calling  [ /usr/sbin/service "${SERVICE_NAME}" status --no-pager --full; ]  ...""\n";
		/usr/sbin/service "${SERVICE_NAME}" status --no-pager --full;

		# Show Jenkins' networking ports
		echo -e "\n""Info: Showing Jenkins' Ports which are in-use";
		echo -e "  |--> Calling  [ ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort'; ]  ...""\n";
		ps aux | grep -v 'grep' | grep 'jenkins' | grep -v 'color=auto' | grep 'httpPort';
		echo "";

		FIREWALL_SERVICE="firewalld";
		SERVICE_RET_CODE=$(/usr/sbin/service "${FIREWALL_SERVICE}" status --no-pager --full 1>'/dev/null' 2>&1; echo $?;);
		if [ ${SERVICE_RET_CODE} -eq 0 ]; then
			# Open necessary firewall port(s)
			SERVICE_ENABLED_GREP=$(/usr/sbin/service "${FIREWALL_SERVICE}" status --no-pager --full | grep '; enabled');
			if [ -n "${SERVICE_ENABLED_GREP}" ]; then
				echo "";
				echo "------------------------------------------------------------";
				firewall-cmd --info-service="${SERVICE_NAME}";
				echo "------------------------------------------------------------";
				echo -e "\n""Info: Opening ports for \"${SERVICE_NAME}\" service in \"${FIREWALL_SERVICE}\" service...\n";
				firewall-cmd --permanent --zone=public --add-service="${SERVICE_NAME}";
				firewall-cmd --reload;
				firewall-cmd --list-all;
				SERVICE_RESTART_REQD=1;
			fi;
		fi;

	else
		EXIT_CODE=1;
		# Jenkins Service STILL not detected after install-attempt
		echo -e "\n""Error:  Jenkins service not detected after install attempt";

	fi;


	# ------------------------------------------------------------
	# Sync jenkins-config to cloud-infrastructure repo (require user confirmation)
	JENKINS_CONFIG_PATH="";
	if [ -f "/etc/default/jenkins" ]; then
		JENKINS_CONFIG_PATH="/etc/default/jenkins";
	elif [ -f "/etc/sysconfig/jenkins" ]; then
		JENKINS_CONFIG_PATH="/etc/sysconfig/jenkins";
	fi;

	if [ -n "${JENKINS_CONFIG_PATH}" ]; then
		echo "";
		# READ_TIMEOUT=60; read -p "Sync Jenkins config-file \"${JENKINS_CONFIG_PATH}\" to \"cloud-infrastructure\" repo, now? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
		# echo "";
		# if [ ${RETURN_CODE_READ} -gt 128 ]; then
		# 	echo -e "Response timed out after ${READ_TIMEOUT}s";
		# elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
		
		CLOUD_SYNC_URL="https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/etc/default/jenkins";
		echo -e "\n""Info: Confirmed - Downloading Jenkins config from \"cloud-infrastructure\" repository";
		echo -e "  |--> Backing-up existing Jenkins config-file to \"${JENKINS_CONFIG_PATH}.${START_TIMESTAMP}.bak\"""\n";
		mv "${JENKINS_CONFIG_PATH}" "${JENKINS_CONFIG_PATH}.${START_TIMESTAMP}.bak";
		wget "${CLOUD_SYNC_URL}" -O "${JENKINS_CONFIG_PATH}" -q;
		chmod 0644 "${JENKINS_CONFIG_PATH}";
		SERVICE_RESTART_REQD=1;
		
		# else
		# 	echo "Denied - Skipping Jenkins config-file sync";
		# fi;
	fi;

	# If a service restart is required, then do so, here
	if [ ${SERVICE_RESTART_REQD} -ne 0 ]; then
		# Make sure to add the port opening
		if [ $(which firewall-cmd 1>'/dev/null' 2>&1; echo $?;) -ne 0 ]; then
			firewall-cmd --permanent --zone=public --add-service="${SERVICE_NAME}"; firewall-cmd --reload;
		fi;
		/usr/sbin/service "${SERVICE_NAME}" restart;
	fi;

	systemctl status jenkins;

	exit ${EXIT_CODE};

fi;

# ------------------------------------------------------------
# Citation(s)
#
#   digitalocean.com  |  "How To Install Jenkins on Ubuntu 16.04"  |  https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-16-04
#
#   docs.oracle.com  |  "java.awt (SE-8) - Class Font"  |  https://docs.oracle.com/javase/8/docs/api/java/awt/Font.html
#
#   docs.oracle.com  |  "Font Configuration Files"  |  https://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html
#
#   hub.docker.com  |  "docker hub - Jenkins Continuous Integration and Delivery server"  |  https://hub.docker.com/r/jenkins/jenkins
#
#   pkg.jenkins.io  |  "Jenkins Debian packages"  |  https://pkg.jenkins.io/debian-stable/
#
#   pkg.jenkins.io  |  "RedHat Linux RPM packages for Jenkins"  |  https://pkg.jenkins.io/redhat-stable/
#
#   wiki.jenkins.io  |  "Jenkins got java.awt.headless problem"  |  https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem
#
# ------------------------------------------------------------