#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_docker" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	if [ -n "$(which get_os 2>'/dev/null';)" ] && [[ "$(get_os)" == *"Microsoft"* ]]; then
		#
		# WSL Docker Installation
		#

		# Redirect Bash calls to Windows docker-host
		ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "/usr/bin/docker";
		ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "/usr/bin/docker-compose";

		# Download Docker Desktop (if not found locally)
		if [ ! -f "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" ]; then
			echo -e "\n""Error: Must install Docker Desktop (for Windows), which WSL will leverage through direct-calls via WSL 2.0 CLI pass-through""\n";
			"/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe";
		else
			"/usr/bin/docker" --version;
			"/usr/bin/docker-compose" --version;
		fi;

		# if [ -v SUDO_USER ]; then
		# 	usermod -aG docker "${SUDO_USER}";
		# fi;
		# usermod -aG docker "${USER}";

		# Redirect Bash calls to Windows docker-host
		ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe" "/usr/bin/docker";
		ln -sf "/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose.exe" "/usr/bin/docker-compose";

	else # ------------------------------------------------------------
		#
		# Non-WSL Docker Installation
		#

		if [ -n "$(which wget 2>/dev/null;)" ]; then
			wget -qO- "https://get.docker.com/" | sh;

		else
			curl -ssL "https://get.docker.com/" | sh;

		fi;

		if [ -z "$(service docker status | grep 'Active: active (running)')" ]; then
			echo "Calling [ service docker start; ]...";
			service docker start;

		else
			service docker status;

		fi;

	fi;

fi;

# ------------------------------------------------------------
# Citation(s)
#
#   stackoverflow.com  |  "Run Docker on Ubuntu on Windows Subsystem for Linux"  |  https://stackoverflow.com/a/48008676
#
#   docs.docker.com  |  "Get Docker CE for Ubuntu"  |  https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1
#
# ------------------------------------------------------------