#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_dotnet" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then

	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;

else
	
	if [[ $(cat /etc/*release | grep -i ubuntu | wc -l) -gt 0 ]]; then
		#
		# UBUNTU Environment
		#
		OS_VERSION_MAJOR=$(cat /etc/*release | grep -i VERSION_ID | sed --regexp-extended --quiet --expression='s/^VERSION_ID="([0-9]+)\.([0-9]+)"$/\1/p');
		OS_VERSION_MINOR=$(cat /etc/*release | grep -i VERSION_ID | sed --regexp-extended --quiet --expression='s/^VERSION_ID="([0-9]+)\.([0-9]+)"$/\2/p');

		if [[ ${OS_VERSION_MAJOR} -ge 19 ]]; then
			# UBUNTU 19.x
			DOWNLOAD_URL="https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb";
			wget -q "${DOWNLOAD_URL}" -O $(basename "${DOWNLOAD_URL}");
			sudo dpkg -i $(basename "${DOWNLOAD_URL}");
			sudo apt-get update -y; sudo apt-get install -y "apt-transport-https";
			sudo apt-get update -y; sudo apt-get install -y "dotnet-sdk-2.2";

		elif [[ ${OS_VERSION_MAJOR} -ge 18 ]]; then
			# UBUNTU 18.x
			DOWNLOAD_URL="https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb";
			wget -q "${DOWNLOAD_URL}" -O $(basename "${DOWNLOAD_URL}");
			sudo dpkg -i $(basename "${DOWNLOAD_URL}");
			sudo apt-get update -y; sudo sudo add-apt-repository -y "universe";
			sudo apt-get update -y; sudo apt-get install -y "apt-transport-https";
			sudo apt-get update -y; sudo apt-get install -y "dotnet-sdk-2.2";

		elif [[ ${OS_VERSION_MAJOR} -ge 16 ]]; then
			# UBUNTU 16.x
			DOWNLOAD_URL="https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb";
			wget -q "${DOWNLOAD_URL}" -O $(basename "${DOWNLOAD_URL}");
			sudo dpkg -i $(basename "${DOWNLOAD_URL}");
			sudo apt-get update -y; sudo apt-get install -y "apt-transport-https";
			sudo apt-get update -y; sudo apt-get install -y "dotnet-sdk-2.2";

		fi;

	fi;

	if [ "$(which dotnet)" == "" ]; then
		# UNKNOWN/UNHANDLED OPERATING SYSTEM
		echo "";
		echo "Unhandled version of Linux:";
		echo "------------------------------------------------------------";
		cat /etc/*release;
		echo "------------------------------------------------------------";
		echo "";
		echo "Please see Microsoft's tutorial page for installing DotNet Core @:";
		echo " |    ";
		echo " |--> https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current";
	fi;

fi;


# -------------------------------------------------------------
#
# Citation(s)
#
#		dotnet.microsoft.com  |  "Install .NET Core SDK on Linux Ubuntu 19.04 - x64"  |  https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
#		dotnet.microsoft.com  |  "Install .NET Core SDK on Linux Ubuntu 18.04 - x64"  |  https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
#		dotnet.microsoft.com  |  "Install .NET Core SDK on Linux Ubuntu 16.04 - x64"  |  https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
#
# ------------------------------------------------------------