#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_ntp" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_ntp" -O "/usr/local/sbin/install_ntp" -q && chmod 0755 "/usr/local/sbin/install_ntp" && /usr/local/sbin/install_ntp;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Install NTP (Time Sync) package "chrony"
	echo "";
	read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync to NTP server(s), now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		PACKAGE_NAME="chrony";
		SERVICE_NAME="chronyd";
		if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
			apt-get -y update; apt-get -y install "${PACKAGE_NAME}"; # Debian, Ubuntu, etc.
		elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then
			yum -y check-update; yum -y install "${PACKAGE_NAME}"; # Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
		fi;
		# ------------------------------------------------------------
		# Sync the system clock to NTP Server(s)
		timedatectl set-ntp yes;
		systemctl restart "${SERVICE_NAME}";
		echo "";
		read -p "$(date +'%Y-%m-%d %H:%M:%S') Sync the hardware clock, now? ( y/n )  " -n 1 -t 60 -r; # Await single keypress
		echo "";
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			# ------------------------------------------------------------
			# Sync the hardware clock to NTP Server(s)
			hwclock --systohc;
			timedatectl set-ntp yes;
		fi;
	fi;
fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   codingbee.net  |  "NTP – Keeping System time in sync on CentOS/RHEL 7"  |  https://codingbee.net/rhcsa/ntp-keeping-system-time-in-sync-on-centos-rhel-7
#
# ------------------------------------------------------------