#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_azwi" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then # RUN THIS SCRIPT

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_azwi?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_azwi_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_azwi"; fi;
mkdir -p "${LOGDIR}"; chown "$(stat -c '%u:%g' "$(dirname "${LOGDIR}";)";)" "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  # Install azwi via the "install_github_pkg" module
  curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_github_pkg?t=$(date +'%s.%N')" | env GITHUB_OWNER="Azure" GITHUB_REPO="azure-workload-identity" VERSION_CLI="version | grep '^Version' | rev | cut -d' ' -f1 | rev | tr -d 'v'" FULLPATH_LOCAL_PKG="/usr/local/bin/azwi" bash;  # install azwi

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   azure.github.io  |  "Azure AD Workload Identity CLI (azwi) - Azure AD Workload Identity"  |  https://azure.github.io/azure-workload-identity/docs/installation/azwi.html
#
#   azure.github.io  |  "Managed Clusters - Azure AD Workload Identity"  |  https://azure.github.io/azure-workload-identity/docs/installation/managed-clusters.html
#
#   docs.microsoft.com  |  "Use Azure Active Directory pod-managed identities in Azure Kubernetes Service (Preview) - Azure Kubernetes Service | Microsoft Docs"  |  https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity
#
#   www.the-aks-checklist.com  |  "AKS-Checklist.pdf"  |  https://www.the-aks-checklist.com/docs/AKS-Checklist.pdf
#
# ------------------------------------------------------------