#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_speedtest" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
if [[ 0 -eq 1 ]]; then  # RUN THIS SCRIPT REMOTELY

curl -H 'Cache-Control: no-cache' -s "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_speedtest?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/install_speedtest_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/install_speedtest"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "${OSTYPE}" == "linux-gnu"* || "$(uname -s)" == "Linux" ]] && [ "$(id -un)" != "root" ]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else

  COMMAND_NAME="speedtest";
  PACKAGE_NAME="speedtest-cli";

  # Ensure that package is installed
  if [ -n "$(command -v ${COMMAND_NAME} 2>'/dev/null';)" ]; then

    # Package is already installed
    echo "";
    echo "Info:  Command \"${COMMAND_NAME}\" already exists with filepath \"$(command -v ${COMMAND_NAME};)\"";

  else

    apt-get -y update;
    apt-get -y install "${PACKAGE_NAME}";

    echo "";
    echo "Info:  Calling [ command -v ${COMMAND_NAME}; ]...";
    command -v ${COMMAND_NAME};

  fi;

  # Verify that package is installed by getting the installed version from it
  echo "";
  echo "Info:  Calling [ ${COMMAND_NAME} --version; ]...";
  ${COMMAND_NAME} --version;

  # Show basic usage for the package
  echo "";
  echo "Info:  To run a verbose speedtest, run [ speedtest; ]";
  echo "";
  echo "Info:  To run a quiet speedtest, run [ speedtest --simple; ]";
  echo "";

fi;


# ------------------------------------------------------------
#
# Citation(s)
# 
#   phoenixnap.com  |  "How to Test Network Speed in Linux {9 Tools} | phoenixNAP KB"  |  https://phoenixnap.com/kb/linux-network-speed-test
#
# ------------------------------------------------------------