#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/install_nginx" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
# Sync 1-Liner
#
if [ 0 -eq 1 ]; then

wget "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/install_nginx" -O "/usr/local/sbin/install_nginx" -q && chmod 0755 "/usr/local/sbin/install_nginx" && /usr/local/sbin/install_nginx;

fi;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	# Install NGINX Web Server
	SERVICE_NAME="nginx";

	if [ $(which apt-get 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then 
		# Debian, Ubuntu, etc.
		apt-get -y update; apt-get -y install "dpkg-dev";
		add-apt-repository "ppa:nginx/stable";
		apt-get -y update; apt-get -y install "nginx-full";

	elif [ $(which yum 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then  # Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
		yum -y check-update; yum -y install "epel-release";
		yum -y check-update; yum -y install "nginx";

	fi;

	/usr/sbin/service "${SERVICE_NAME}" start;

	# ------------------------------------------------------------
	# Setup NGINX
	if [ $(which "${SERVICE_NAME}" 1>'/dev/null' 2>&1; echo $?;) -eq 0 ]; then

		# Check Service Status
		nginx -v;
		/usr/sbin/service "${SERVICE_NAME}" status;

		# Update Diffie-Hellman Parameter
		if [ ! -f "/etc/ssl/certs/dhparam.pem" ]; then
			DH_KEY_SIZE_BITS=2048;
			echo "Creating Diffie-Hellman parameter with key size of [ ${DH_KEY_SIZE_BITS}-bit ] @ filepath \"/etc/ssl/certs/dhparam.pem\"...";
			openssl dhparam -out "/etc/ssl/certs/dhparam.pem" ${DH_KEY_SIZE_BITS};
		fi;

	fi;


	if [ 0 -eq 1 ]; then
	# ------------------------------------------------------------
	# Install Geo-IP Module
		# Module ngx_stream_geoip_module  :::  http://nginx.org/en/docs/stream/ngx_stream_geoip_module.html
		# Module ngx_http_geoip_module  :::  http://nginx.org/en/docs/http/ngx_http_geoip_module.html
		add-apt-repository ppa:maxmind/ppa;
		apt -y update;
		apt -y install geoip-database geoip-database-extra php-geoip;
		apt -y install geoipupdate;
		apt-get -y clean; apt -y autoremove;

		# locate the geoip databases
		dpkg -L geoip-database | grep '\.dat'; dpkg -L geoip-database-extra  | grep '\.dat';
	fi;


fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   www.digitalocean.com  |  "How To Install Nginx on Ubuntu 16.04 | DigitalOcean"  |  https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04
#
#   www.digitalocean.com  |  "How To Install Nginx on CentOS 7 | DigitalOcean"  |  https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7
#
# ------------------------------------------------------------