#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/jenkins_export_config" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else

	# ------------------------------------------------------------

	START_TIMESTAMP="$(date +'%Y-%m-%d_%H-%M-%S')";

	TARGET_USER="jenkins";

	REPO_CREDS="${HOME}/.ssh/jenkins-config.push";

	shopt -s "globstar";

	# Determine user's home-directory location
	if [ -z "${JENKINS_HOME}" ] || [  ! -d "${JENKINS_HOME}" ]; then
		JENKINS_HOME=$(getent passwd "${TARGET_USER}" | cut --delimiter=: --fields=6);
	fi;

	if [ -n "${JENKINS_HOME}" ] && [ -d "${JENKINS_HOME}" ]; then

		# ------------------------------------------------------------
		# Export all 'config.xml' (jenkins-config) files

		FILEPATH_ARCHIVE_7Z_CONFIG="${HOME}/jenkins_export_config.${START_TIMESTAMP}.7z";
	
		# echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Calling [ du -sh \"${JENKINS_HOME}/**/config.xml\" ]...\n";
		# du -sh "${JENKINS_HOME}/**/config.xml";

		echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Compressing \"${JENKINS_HOME}/**/config.xml\" into \"${FILEPATH_ARCHIVE_7Z_CONFIG}\"...\n";
		cd "$(dirname ${JENKINS_HOME})" && \
		find "$(basename ${JENKINS_HOME})/" \
			-mindepth 1 \
			-maxdepth 3 \
			-name 'config.xml' \
			-not -path "./config-history/*" \
			-type f \
			-exec 7z u "${FILEPATH_ARCHIVE_7Z_CONFIG}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -spf -spe '{}' \; ;

		GIT_WORK_TREE=$(git_init "${REPO_CREDS}" | grep -e '^/var/lib/git') && \
		cd "${GIT_WORK_TREE}" && \
		chmod 0600 "${FILEPATH_ARCHIVE_7Z_CONFIG}" && \
		mkdir -p "./config-exports/" && \
		mv "${FILEPATH_ARCHIVE_7Z_CONFIG}" "./config-exports/." && \
		shopt -s "globstar" && \
		source "${REPO_CREDS}" && \
		env \
			GIT_SSH_COMMAND="ssh -i \"${REMOTE_PRIVATE_KEY}\" -o StrictHostKeyChecking=no -F /dev/null" \
			GIT_CURL_VERBOSE="1" \
			GIT_AUTHOR_NAME="${REMOTE_USERNAME}" \
			GIT_COMMITTER_NAME="${REMOTE_USERNAME}" \
			GIT_AUTHOR_EMAIL="${REMOTE_EMAIL}" \
			GIT_COMMITTER_EMAIL="${REMOTE_EMAIL}" \
			EMAIL="${REMOTE_EMAIL}" \
		git add ./**/*.7z && \
		git commit -m"${START_TIMESTAMP} | Exported Jenkins config-files from $(hostname)" -a && \
		git push;

		# ------------------------------------------------------------
		# Export all files contained in the 'plugins' directory
	
		FILEPATH_ARCHIVE_7Z_PLUGINS="${HOME}/jenkins_export_plugins.${START_TIMESTAMP}.7z";

		echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Calling [ du -sh \"${JENKINS_HOME}/plugins/\" ]...\n";
		du -sh "${JENKINS_HOME}/plugins/";

		echo -e "\n$(date +'%Y-%m-%d %H:%M:%S') | Compressing \"$(basename ${JENKINS_HOME})/plugins/\" into \"${FILEPATH_ARCHIVE_7Z_PLUGINS}\" (split into 100-MB incremenets)...\n";
		cd "$(dirname ${JENKINS_HOME})" && \
		7z -v100m a "${FILEPATH_ARCHIVE_7Z_PLUGINS}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -spf -spe "${JENKINS_HOME}/plugins/";

		GIT_WORK_TREE=$(git_init "${REPO_CREDS}" | grep -e '^/var/lib/git') && \
		cd "${GIT_WORK_TREE}" && \
		chmod 0600 "${FILEPATH_ARCHIVE_7Z_PLUGINS}"* && \
		mkdir -p "./plugin-exports/${START_TIMESTAMP}/" && \
		mv "${FILEPATH_ARCHIVE_7Z_PLUGINS}"* "./plugin-exports/${START_TIMESTAMP}/." && \
		shopt -s "globstar" && \
		source "${REPO_CREDS}" && \
		env \
			GIT_SSH_COMMAND="ssh -i \"${REMOTE_PRIVATE_KEY}\" -o StrictHostKeyChecking=no -F /dev/null" \
			GIT_CURL_VERBOSE="1" \
			GIT_AUTHOR_NAME="${REMOTE_USERNAME}" \
			GIT_COMMITTER_NAME="${REMOTE_USERNAME}" \
			GIT_AUTHOR_EMAIL="${REMOTE_EMAIL}" \
			GIT_COMMITTER_EMAIL="${REMOTE_EMAIL}" \
			EMAIL="${REMOTE_EMAIL}" \
		git add ./**/*.7z && \
		git commit -m"${START_TIMESTAMP} | Exported Jenkins plugins from $(hostname)" -a && \
		git push;

		# ------------------------------------------------------------

	fi;

fi;

# ------------------------------------------------------------
# 
# Citation(s)
#	
# 	devops.stackexchange.com  |  "How do you back up Jenkins jobs & master configs?"  |  https://devops.stackexchange.com/a/563
# 
# ------------------------------------------------------------
