#!/bin/bash

START_TIMESTAMP="$(date +'%Y-%m-%d_%H-%M-%S')";

TARGET_USER="jenkins";

FILEPATH_ARCHIVE_7Z="/${HOME}/${TARGET_USER}_config-export.${START_TIMESTAMP}.7z";

# Determine user's home-directory location
if [ -z "${JENKINS_HOME}" ] || [  ! -d "${JENKINS_HOME}" ]; then
	JENKINS_HOME=$(getent passwd "${TARGET_USER}" | cut --delimiter=: --fields=6);
fi;

if [ -n "${JENKINS_HOME}" ] && [ -d "${JENKINS_HOME}" ]; then

	cd $JENKINS_HOME;

	git_init "$HOME/.ssh/jenkins-config.pull";

# ------------------------------------------------------------

find "${JENKINS_HOME}/" \
-mindepth 1 \
-maxdepth 3 \
-name 'config.xml' \
-not -path "${JENKINS_HOME}/config-history/*" \
-type f \
-exec 7z a "${FILEPATH_ARCHIVE_7Z}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on '{}';
;

# 7z a "${FILEPATH_ARCHIVE_7Z}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on '{}';
# 7z a "${FILEPATH_ARCHIVE_7Z}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on '{}' > /dev/null;

# ------------------------------------------------------------

	# git init;
	# shopt -s globstar; # If set, the pattern ‘**’ used in a filename expansion context will match all files and zero or more directories and subdirectories. If the pattern is followed by a ‘/’, only directories and subdirectories match.
	# git add **/config.xml;
	# git commit --message="${START_TIMESTAMP} | Backing-up Jenkins config-scripts" --all;

fi;

# ------------------------------------------------------------
# 
# Citation(s)
#	
# 	devops.stackexchange.com  |  "How do you back up Jenkins jobs & master configs?"  |  https://devops.stackexchange.com/a/563
# 
# ------------------------------------------------------------
