#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/jenkins_war_update" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
[ -w "/var/log/" ] && LOGDIR="/var/log/${0}" || LOGDIR="~/log/${0}"; mkdir -p "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')" && echo "" > "${LOGFILE}" && chmod 600 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then

	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;

else

	echo "===== ------------------------------------------------------------ =====";
	echo "$(date +'%D  %r')   Starting ${0}...";

	# Base-directory for Jenkins ".war" file
	WAR_DIR="/usr/share/jenkins"

	# Backup the current Jenkins main-executable (jenkins.war)
	JENKINS_SYSTEM_RUNTIME="${WAR_DIR}/jenkins.war";
	JENKINS_BACKUP_RUNTIME="${JENKINS_SYSTEM_RUNTIME}.$(date +'%Y%m%d_%H%M%S').bak";

	rm -f "${JENKINS_BACKUP_RUNTIME}";
	cp -f "${JENKINS_SYSTEM_RUNTIME}" "${JENKINS_BACKUP_RUNTIME}";

	# Stop the Jenkins-Service while we update
	echo "$(date +'%D  %r')   Stopping Jenkins Service...";
	systemctl stop jenkins

	# Download an updated version of the Jenkins main-executable (jenkins.war)
	echo "$(date +'%D  %r')   Downloading Most-Recent Version of Jenkins...";
	
	WGET_LOGFILE="${LOGDIR}/wget_updated_warfile.$(date +'%Y%m%d_%H%M%S').log";
	if [ -f "${WGET_LOGFILE}" ]; then rm -f "${WGET_LOGFILE}"; fi;

	DOWNLOAD_URL="https://updates.jenkins-ci.org/latest/jenkins.war";
	wget --quiet --server-response --output-document="${JENKINS_SYSTEM_RUNTIME}" --output-file="${WGET_LOGFILE}" "${DOWNLOAD_URL}";

	# Verify that download actually downloaded more than 0 bytes
	NEW_WAR_FILESIZE=$(du -sh "${JENKINS_SYSTEM_RUNTIME}" | awk '{print $1}');
	echo "NEW_WAR_FILESIZE = \"${NEW_WAR_FILESIZE}\"";
	if [[ ! -n "${NEW_WAR_FILESIZE}" ]] || [[ "${NEW_WAR_FILESIZE}" == "" ]] || [[ "${NEW_WAR_FILESIZE}" == "0" ]]; then
		echo "";
		echo "Empty runtime detected: \"${JENKINS_SYSTEM_RUNTIME}\"";
		echo "Reverting to previous runtime: \"${JENKINS_BACKUP_RUNTIME}\"";
		rm -f "${JENKINS_SYSTEM_RUNTIME}";
		cp -f "${JENKINS_BACKUP_RUNTIME}" "${JENKINS_SYSTEM_RUNTIME}";
	else
		echo "Non-empty Jenkins.war runtime found - Proceeding...";
	fi;

	# Log the relevant info from the version which was just downloaded
	printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Location: ${DOWNLOAD_URL}";
	printf "$(date +'%D  %r')   " && cat "${WGET_LOGFILE}" | grep "Last-Modified: ";
	rm -f "${WGET_LOGFILE}";

	# Start the Jenkins-Service now that we're finished updating
	echo "$(date +'%D  %r')   Starting Jenkins...";
	systemctl start jenkins;

	# Reload NGINX
	echo "$(date +'%D  %r')   Reloading NGINX...";
	sudo nginx -t;
	sleep 3;
	sudo systemctl reload nginx;

	# Exit Gracefully
	echo "$(date +'%D  %r')   Finished ${0}";
	exit 0;

fi;