#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/mysql_reset_root_passwd" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else

	ROOT_MYSQL_PASSWD_PATH="${HOME}/mysql_root_passwd";
	if [ ! -f "${ROOT_MYSQL_PASSWD_PATH}" ]; then
		echo "To reset MySQL root password, place new password in filepath \"${ROOT_MYSQL_PASSWD_PATH}\" as one single line of text (no newlines)";
		exit 1;
	elif [ $(cat "${ROOT_MYSQL_PASSWD_PATH}" | wc -l;) -gt 1 ]; then
		echo "To reset MySQL root password, place new password in filepath \"${ROOT_MYSQL_PASSWD_PATH}\" as ONE SINGLE LINE of text (no newlines)";
		exit 1;
	fi;
	chmod 0400 "${ROOT_MYSQL_PASSWD_PATH}";
	ROOT_MYSQL_PASSWD=$(cat "${ROOT_MYSQL_PASSWD_PATH}");

	MYSQL_INIT_PATH="${HOME}/mysql-init";
	MYSQL_RESET_ROOT_PASSWD="ALTER USER 'root'@'localhost' IDENTIFIED BY '${ROOT_MYSQL_PASSWD}';" > "${MYSQL_INIT_PATH}";
	echo "${MYSQL_RESET_ROOT_PASSWD}" > "${MYSQL_INIT_PATH}";
	chmod 0440 "${MYSQL_INIT_PATH}";
	chown "root:mysql" "${MYSQL_INIT_PATH}";

	echo -e "\n";
	read -p "Are you ready to reset the root MySQL password? (y/n)  " -n 1 -t 60 -r; RETURN_CODE_READ=$?;
	echo "";
	if [ ${RETURN_CODE_READ} -gt 128 ]; then
		echo -e "Response timed out";
	elif [ -n "${REPLY}" ] && [[ $REPLY =~ ^[Yy]$ ]]; then
		echo -e "\n""Info: Confirmed - Attempting to reset the root MySQL password...""\n";

		# kill $(cat /var/run/mysqld/mysqld.pid);
		service mysqld stop;

		service mysqld start;

	else
		echo "Denied - Skipping command";
	fi;

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   confluence.atlassian.com  |  "Database Setup For MySQL - Atlassian Documentation"  |  https://confluence.atlassian.com/doc/database-setup-for-mysql-128747.html
#
#   dev.mysql.com  |  "MySQL :: MySQL 5.7 Reference Manual :: B.4.3.2 How to Reset the Root Password"  |  https://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html
#
# ------------------------------------------------------------