#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/reload_nginx" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------

	SERVICE_NAME="nginx";

	SERVICE_MATCHES=$(service --status-all 2>/dev/null | sed --regexp-extended --quiet --expression='s/^\ \[ (\+|\-) \]\ \ ('${SERVICE_NAME}')$/\2/p');
	
	if [ "${SERVICE_NAME}" == "${SERVICE_MATCHES}" ]; then

		# Service found to exist locally

		# echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ service nginx status; ] (before reload)...";
		# service nginx status;

		if [ -f "/run/nginx.pid" ]; then
			echo "$(date +'%Y-%m-%d %H:%M:%S') | $(basename ${0}): Reloading NGINX Service...";
			sudo nginx -t && sudo sleep 1 && sudo service nginx reload;
		else
			# Get PIDs (Process-IDs) for any non-primary/rogue nginx runtime(s)
			PID_ROGUE_NGINX_INSTANCE=$(netstat -nlp | grep :80 | grep nginx | awk '{print $7}' | cut -d/ -f 1);
			if [ -n "${PID_ROGUE_NGINX_INSTANCE}" ]; then
				# Snipe rogue nginx PIDs
				echo "$(date +'%Y-%m-%d %H:%M:%S') | $(basename ${0}): Killing Rogue NGINX Instance...";
				sudo kill "${PID_ROGUE_NGINX_INSTANCE}";
			fi;
			# Start nginx service, again
			echo "$(date +'%Y-%m-%d %H:%M:%S') | $(basename ${0}): Starting NGINX Service...";
			sudo nginx -t && sudo sleep 1 && sudo service nginx start;
		fi;

		# echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ service nginx status; ] (after reload)...";
		# service nginx status;
		
	else
	
		# Service NOT found to exist locally
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Error - service \"${SERVICE_NAME}\" not found amongst local services";

	fi;
fi;
