#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/reload_httpd" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/reload_httpd_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/reload_httpd"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d')"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  #
  # Reload Httpd (Apache/Aapache2) service
  #
  SERVICE_NAME="httpd";
  SERVICE_RET_CODE=$(/bin/systemctl list-unit-files --no-legend --no-pager --full "${SERVICE_NAME}.service" | grep "^${SERVICE_NAME}.service" 1>'/dev/null' 2>&1; echo $?;);
  if [ ${SERVICE_RET_CODE} -ne 0 ]; then
    # Service NOT found to exist locally
    echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Service \"${SERVICE_NAME}\" not found amongst local services";

  else
    # Service EXISTS locally
    if [ -f "/etc/init.d/apache2" ]; then
      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) reload_httpd: Reloading Apache2 (httpd) via command  [ /etc/init.d/apache2 reload; ]...";
      /etc/init.d/apache2 reload;
    elif [ -n "$(which httpd 2>'/dev/null';)" ]; then
      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) reload_httpd: Reloading Apache (httpd) via command  [ httpd -t && httpd -k restart; ]...";
      httpd -t && httpd -k restart;
    else
      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Apache2 initialization file \"/etc/init.d/apache2\" not found";
      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Apache runtime \"httpd\" not found";
    fi;

  fi;

fi;


# ------------------------------------------------------------
#
# Citation(s)
#
#   stackoverflow.com  |  "apache2 - How to reload apache configuration for a site without restarting apache - Stack Overflow"  |  https://stackoverflow.com/a/8270181
#
# ------------------------------------------------------------
