#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/remove_package" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/remove_package_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/remove_package"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  exit 1;
else
  # ------------------------------------------------------------
  #
  # Remove package(s)
  #

  if [ -z "${1}" ]; then

    # Required variable empty
    echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: No value given for first parameter (\$1)";
    echo "Please set \$1 to [ package-name-to-remove ]\" & re-run this script";
    echo "  ( e.g. ${0} \"wget\"; )";
    echo "";
    exit 1;

  else

    PACKAGE_NAME="$1";

    echo "";
    read -p "$(date +'%Y-%m-%dT%H:%M:%S.%N%z';) Remove package \"${PACKAGE_NAME}\", now? ( y/n )  " -n 1 -t 60 <'/dev/tty'; # Await single keypress
    echo "";

    if [[ $REPLY =~ ^[Yy]$ ]]; then

      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Confirmed - Removing package \"${PACKAGE_NAME}\"...";

      apt-get -y remove "${PACKAGE_NAME}";

      apt-get -y purge "${PACKAGE_NAME}";

      apt-get -y autoremove;

      apt-get -y autoclean;

      remove_service "${PACKAGE_NAME}";

    else

      echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Cancelled - No Action Taken";

    fi;

    echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Finished - Exiting...";
    echo "";
    exit;
    
  fi;

  # ------------------------------------------------------------

fi;
