#!/bin/bash
SSHD_CONFIG="/etc/ssh/sshd_config" && \
SSHD_BAK="/etc/ssh/sshd_config.tmp.bak" && \
SSHD_UPD="/etc/ssh/sshd_config.update";
if [[ "$(hostname)" == "aws-3" ]] || [[ "$(curl https://icanhazip.com)" == "$(dig +short aws-3.boneal.net)" ]] || [[ "$(hostname)" == "raspi-4b" ]]; then
	if [[ ! -f "${SSHD_BAK}" ]]; then
		REPO_FILE="https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/etc/ssh/sshd_config.update" && \
		wget "${REPO_FILE}" --output-document="${SSHD_UPD}" && \
		chmod 0644 "${SSHD_UPD}" && \
		cp -f "${SSHD_CONFIG}" "${SSHD_BAK}" && \
		cp -f "${SSHD_UPD}" "${SSHD_CONFIG}" && \
		service ssh restart;
	fi;
fi;
