#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/ufw_ipv6_setup" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	RESTART_SERVICE_UFW=0;
	# ------------------------------------------------------------
	#
	# UFW | Service Check
	#  |--> Fail-out if UFW does NOT exist as local service
	#
	SERVICE_NAME="ufw";
	SERVICE_MATCHES=$(service --status-all 2>/dev/null | sed --regexp-extended --quiet --expression='s/^\ \[ (\+|\-) \]\ \ ('${SERVICE_NAME}')$/\2/p');
	if [ -z "${SERVICE_MATCHES}" ]; then
		echo "Error - Service \"${SERVICE_NAME}\" NOT found as a local service";
		exit 1;
	else
		# ------------------------------------------------------------
		#
		# UFW | IPv6 Pinging
		#  |--> Check whether UFW currently allows IPv6 Ping requests or not, then asks to enable/disable it (depending on status)
		#
		ALLOW_ICMPv6_ECHO=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type echo-request -j ACCEPT$/\0/p');
		if [ -n "${ALLOW_ICMPv6_ECHO}" ]; then
			echo -e "\n""IPv6 Pinging is currently ENABLED";
			read -p "DISABLE IPv6 Pinging, Now? ( Y/N )  " -n 1 -t 20 -r; echo "";
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				sed \
					--regexp-extended \
					--in-place=".$(date +'%Y-%m-%d_%H-%M-%S').bak" \
					--expression='/^# Allow ICMPv6 Pinging$/d' \
					--expression='/^-A ufw6-before-input -p icmpv6 --icmpv6-type echo-request -j ACCEPT$/d' \
					"/etc/ufw/before6.rules";
				RESTART_SERVICE_UFW=1;
			fi;
		else
			echo -e "\n""IPv6 Pinging is currently DISABLED"; read -p "ENABLE IPv6 Pinging, Now? ( Y/N )  " -n 1 -t 20 -r;
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				sed \
					--regexp-extended \
					--in-place=".$(date +'%Y-%m-%d_%H-%M-%S').bak" \
					--expression='/^#.+line or these rules.+$/d' \
					--expression='/^COMMIT$/i\# Allow ICMPv6 Pinging\n-A ufw6-before-input -p icmpv6 --icmpv6-type echo-request -j ACCEPT\n# dont delete the COMMIT line or these rules wont be processed' \
					"/etc/ufw/before6.rules";
				RESTART_SERVICE_UFW=1;
			fi;
		fi;
		# ------------------------------------------------------------
		#
		# UFW | IPv6 Multicast
		#  |--> Check whether UFW currently allows IPv6 Multicast requests or not, then asks to enable/disable it (depending on status)
		#
		ALLOW_ICMPv6_MULTICAST=$(cat "/etc/ufw/before6.rules" | sed --regexp-extended --quiet --expression='s/^-A ufw6-before-input -p icmpv6 --icmpv6-type 130 -j ACCEPT$/\0/p');
		if [ -n "${ALLOW_ICMPv6_MULTICAST}" ]; then
			echo -e "\n""IPv6 Multicast is currently ENABLED";
			read -p "DISABLE IPv6 Multicast, Now? ( Y/N )  " -n 1 -t 20 -r; echo "";
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				sed \
					--regexp-extended \
					--in-place=".$(date +'%Y-%m-%d_%H-%M-%S').bak" \
					--expression='/^# Allow ICMPv6 Multicast$/d' \
					--expression='/^-A ufw6-before-input -p icmpv6 --icmpv6-type 130 -j ACCEPT$/d' \
					"/etc/ufw/before6.rules";
				RESTART_SERVICE_UFW=1;
			fi;
		else
			echo -e "\n""IPv6 Multicast is currently DISABLED";
			read -p "ENABLE IPv6 Multicast, Now? ( Y/N )  " -n 1 -t 20 -r;
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				sed \
					--regexp-extended \
					--in-place=".$(date +'%Y-%m-%d_%H-%M-%S').bak" \
					--expression='/^#.+line or these rules.+$/d' \
					--expression='/^COMMIT$/i\# Allow ICMPv6 Multicast\n-A ufw6-before-input -p icmpv6 --icmpv6-type 130 -j ACCEPT\n# dont delete the COMMIT line or these rules wont be processed' \
					"/etc/ufw/before6.rules";
				RESTART_SERVICE_UFW=1;
			fi;
		fi;
		# ------------------------------------------------------------
		# Restart necessary service(s)
		# ------------------------------------------------------------
		if [ ${RESTART_SERVICE_UFW} -eq 1 ]; then
			service ufw restart;
			# service ufw status;
		fi;
	fi;
fi;

# ------------------------------------------------------------
#
# Citation(s)
#
#		digitalocean.com  |  "UFW Essentials: Common Firewall Rules and Commands"  |  https://www.digitalocean.com/community/tutorials/ufw-essentials-common-firewall-rules-and-commands
#
#		digitalocean.com  |  "How To Set Up a Firewall with UFW on Ubuntu 18.04"  |  https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-18-04
#
#		askubuntu.com  |  "How to enable ufw firewall to allow icmp response?"  |  https://askubuntu.com/a/10314
#
#		manpages.ubuntu.com  |  "Ubuntu manuals - NAME"  |  https://manpages.ubuntu.com/manpages/trusty/man8/ufw.8.html
#
# ------------------------------------------------------------
