#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/update_bins_from_sftp" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------
	
	# Make sure required runtime(s) are installed
	if [ -z "$(which dos2unix)" ]; then
		apt-get-update -y; apt-get install -y dos2unix;
	fi;
	
	UPDATE_FROM_DIR="";

	# Detect & handle WSL instance(s)

	WIN32_USERNAME=$(wsl_get_windows_username);
	if [ -n "${WIN32_USERNAME}" ]; then
		#  Windows Subsystem for Linux - Update from files in Host-User's files
		WIN32_HOMEDIR=$(find /mnt/*/Users/${WIN32_USERNAME} -mindepth 0 -maxdepth 0 -type d);
		WIN32_USR_LOCAL=$(find ${WIN32_HOMEDIR}/Documents -maxdepth 10 -name 'local' -type d | grep '/cloud-infrastructure/usr/local');

		echo "";
		echo "WIN32_USERNAME = [${WIN32_USERNAME}]";

		echo "";
		echo "WIN32_HOMEDIR = [${WIN32_HOMEDIR}]";

		echo "";
		echo "WIN32_USR_LOCAL = [${WIN32_USR_LOCAL}]";

		if [ ! -n "${WIN32_USR_LOCAL}" ]; then
			echo "";
			echo "Unable to locate directory matching 'cloud-infrastructure/usr/local' within win32-user's documents @ '${WIN32_USERNAME}'";
			exit 1;
		else
			UPDATE_FROM_DIR="$(dirname ${WIN32_USR_LOCAL})";
		fi;
	else
		#  Linux OS - Update Bin-commands from SFTP-dropped files
		UPDATE_FROM_DIR="$(getent passwd ${SUDO_USER} | cut --delimiter=: --fields=6)";
	fi;

	if [ ! -d "${UPDATE_FROM_DIR}/local/bin/" ] || [ ! -d "${UPDATE_FROM_DIR}/local/sbin/" ]; then
		# Error-out (before copying-files) if any required copy-from directories are missing
		if [ ! -d "${UPDATE_FROM_DIR}/local/bin/" ]; then
			echo "";
			echo "Error - Directory not-found: [ ${UPDATE_FROM_DIR}/local/bin/ ]";
		fi;
		if [ ! -d "${UPDATE_FROM_DIR}/local/sbin/" ]; then
			echo "";
			echo "Error - Directory not-found: [ ${UPDATE_FROM_DIR}/local/sbin/ ]";
		fi;
		exit 1;

	else

		echo "";
		echo "Copying files from '${UPDATE_FROM_DIR}/local/bin/*' to '/usr/local/bin/.'";
		sudo cp --verbose --force ${UPDATE_FROM_DIR}/local/bin/* /usr/local/bin/.;
		sudo chown "root:root" /usr/local/bin/*;
		sudo chmod 0755 /usr/local/bin/*;
		sudo dos2unix /usr/local/bin/*;

		echo "";
		echo "Copying files from '${UPDATE_FROM_DIR}/local/sbin/*' to '/usr/local/sbin/.'";
		sudo cp --verbose --force ${UPDATE_FROM_DIR}/local/sbin/* /usr/local/sbin/.;
		sudo chown "root:root" /usr/local/sbin/*;
		sudo chmod 0755 /usr/local/sbin/*;
		sudo dos2unix /usr/local/sbin/*;

		exit 0;

	fi;

fi;
