#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/update_unifi" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/$(basename ${0})_logs"; if [ -w "/var/log/" ]; then LOGDIR="/var/log/$(basename ${0})"; fi;
mkdir -p "${LOGDIR}"; chown $(stat -c '%u:%g' $(dirname ${LOGDIR})) "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date +'%Y%m%d_%H%M%S')"; echo -n "" > "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" );
exec 2>&1;
#
# ------------------------------------------------------------
#
# Script must run as root or via sudo
#
if [ "$(id -un)" != "root" ]; then
	echo "";
	echo "$(date +'%Y-%m-%d %H:%M:%S') | Error: Script must run as user \"root\" or via \"sudo\" command";
	exit 1;
else
	# ------------------------------------------------------------

	SERVICE_NAME="unifi";
	SERVICE_MATCHES=$(/bin/systemctl list-unit-files --no-legend | awk '{print $1}' | sed -rne 's/^([A-Za-z0-9\.\_\-]+)\.service$/\1/p' | awk "/^${SERVICE_NAME}$/{print \$0}" | sort 2> '/dev/null';);
	if [ -n "${SERVICE_MATCHES}" ]; then # Service exists locally
		# Show service status
		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ /bin/systemctl status \"unifi\" --no-pager --full; ] (before potential update)...";
		/bin/systemctl status "unifi" --no-pager --full;

		# Update UniFi
		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ apt-get update -y; ]...";
		apt-get update -y;

		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ echo \"unifi unifi/has_backup boolean true\" | debconf-set-selections; ]...";
		echo "unifi unifi/has_backup boolean true" | debconf-set-selections;

		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ DEBIAN_FRONTEND=noninteractive apt-get install --only-upgrade unifi && /bin/systemctl restart \"unifi\"; ]...";
		DEBIAN_FRONTEND=noninteractive apt-get install --only-upgrade unifi && /bin/systemctl restart "unifi";


		# Show service status
		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Calling [ /bin/systemctl status \"unifi\" --no-pager --full; ] (after potential update)...";
		/bin/systemctl status "unifi" --no-pager --full;

	else # Service NOT found to exist as a local service
		echo "";
		echo "$(date +'%Y-%m-%d %H:%M:%S') | Info: Update Skipped - Service \"${SERVICE_NAME}\" not found amongst local services";
	fi;

fi;
