#!/bin/bash
#
# LOCAL_SBIN="/usr/local/sbin/wsl_autostart_cron" && echo "" > "${LOCAL_SBIN}" && vi "${LOCAL_SBIN}" && chmod 0755 "${LOCAL_SBIN}";
#
# ------------------------------
if [[ 0 -eq 1 ]]; then # RUN THIS SCRIPT REMOTELY:

curl -H "Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" -ssL "https://raw.githubusercontent.com/mcavallo-git/cloud-infrastructure/master/usr/local/sbin/wsl_autostart_cron?t=$(date +'%s.%N')" | bash;

fi;
# ------------------------------------------------------------
#
# Log all shell output & error output to logfile
#
LOGDIR="${HOME}/wsl_autostart_cron_logs"; if [[ -w "/var/log/" ]]; then LOGDIR="/var/log/wsl_autostart_cron"; fi;
mkdir -p "${LOGDIR}"; chown "$(stat -c '%u:%g' "$(dirname "${LOGDIR}";)";)" "${LOGDIR}"; chmod 0770 "${LOGDIR}";
LOGFILE="${LOGDIR}/$(basename ${LOGDIR})_$(date --utc +'%Y%m%d';)"; touch "${LOGFILE}"; chmod 0660 "${LOGFILE}";
exec > >(tee -a "${LOGFILE}" ); printf -- '-%.0s' {1..10}; printf " Script started at [ $(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) ]\n";
exec 2>&1;
# ------------------------------

EXIT_CODE=0;

SERVICE_NAME="cron";

# ------------------------------
#
# Script must run as root (or via sudo)
#
if [[ "$(id -un)" != "root" ]]; then
  echo "";
  echo "$(date --utc +'%Y-%m-%dT%H:%M:%S.%NZ';) Error: Script must run as user \"root\" or via \"sudo\" command";
  EXIT_CODE=$(( ${EXIT_CODE:-0} + 1 ));
else

  FULLPATH_SERVICE_AUTOSTART="/etc/profile.d/wsl_autostart_${SERVICE_NAME}";

  ACTION_DESCRIPTION="Apply auto-start for service '${SERVICE_NAME}' via file '${FULLPATH_SERVICE_AUTOSTART}'";

  if [[ -n "$(uname -r 2>&1 | grep -i 'microsoft' 2>&1;)" ]]; then
    #
    # WSL environment detected
    #
    # Get fullpath to wsl.exe
    WSL_DISTRO_NAME="${WSL_DISTRO_NAME:-$(IFS='\'; FULLPATH_ROOT_DIR=($(wslpath -w /)); echo "${FULLPATH_ROOT_DIR[${#FULLPATH_ROOT_DIR[@]}-1]}";)}";
    WSL_EXE="$(if [[ -n "$(command -v wsl.exe 2>'/dev/null';)" ]]; then echo "$(realpath "$(command -v "wsl.exe";)" 2>'/dev/null';)"; elif [[ -f "$(find /mnt/*/Windows/System32/wsl.exe -mindepth 0 -maxdepth 0 -type f | head -n 1;)" ]]; then find /mnt/*/Windows/System32/wsl.exe -mindepth 0 -maxdepth 0 -type f | head -n 1; else echo "$(wslpath -u "$(wslvar -s "ComSpec";)";)"; fi;)";
    # Apply service auto-start
    echo "";
    echo "Info:  Performing action [ ${ACTION_DESCRIPTION} ]...";
    echo "";

    echo -e "\nif [[ \$(/usr/sbin/service ${SERVICE_NAME} status 1>/dev/null 2>&1; echo \${?};) -ne 0 ]]; then\n  # Auto-start service [ ${SERVICE_NAME} ] whenever a bash terminal is opened\n ${WSL_EXE} -d ${WSL_DISTRO_NAME} -u root -e /usr/sbin/service ${SERVICE_NAME} start 1>/dev/null 2>&1;\nfi;\n" > "${FULLPATH_SERVICE_AUTOSTART}";
    chmod -R "0755" "${FULLPATH_SERVICE_AUTOSTART}";
  else
    #
    # Error - Non-WSL environment detected
    #
    echo "";
    echo "Error:  Non-WSL environment/OS detected";
    echo " |";
    echo " |--> Skipping action [ ${ACTION_DESCRIPTION} ]";
    echo "";
    EXIT_CODE=$(( ${EXIT_CODE:-0} + 1 ));
  fi;
fi;

# Exit cleanly
exit ${EXIT_CODE:-0};

# ------------------------------------------------------------
#
# Citation(s)
#
#   github.com  |  "Q: Identify distro from within distro, under WSL · Issue #4479 · microsoft/WSL · GitHub"  |  https://github.com/microsoft/WSL/issues/4479#issuecomment-876698799
#
# ------------------------------------------------------------